import 'package:flutter/material.dart';

final ValueNotifier<String> localeNotifier = ValueNotifier('en');

class Lang {
  static final Map<String, Map<String, String>> _data = _buildData();

  static Map<String, Map<String, String>> _buildData() {
    final e = <String, String>{};
    final b = <String, String>{};
    void p(String k, String ev, String bv) { e[k] = ev; b[k] = bv; }

    p('appTitle', 'AL ASHAB', 'আল আসহাব');
    p('overview', 'Overview', 'সারসংক্ষেপ');
    p('dailySales', 'Daily Sales', 'দৈনিক বিক্রি');
    p('stock', 'Stock', 'স্টক');
    p('dues', 'Dues', 'বাকি');
    p('expenses', 'Expenses', 'খরচ');
    p('investor', 'Investor', 'বিনিয়োগকারী');
    p('customers', 'Customers', 'গ্রাহক');
    p('stockAndAssets', 'Stock & Assets', 'স্টক ও সম্পদ');
    p('expensesAndPurchases', 'Expenses & Purchases', 'খরচ ও কেনাকাটা');
    p('utilities', 'UTILITIES', 'সহায়ক');
    p('quickCaptures', 'Quick Captures', 'দ্রুত নোট');
    p('fixedAssets', 'Fixed Assets', 'স্থায়ী সম্পদ');
    p('data', 'DATA', 'তথ্য');
    p('exportData', 'Export Data', 'ডেটা এক্সপোর্ট');
    p('importData', 'Import Data', 'ডেটা ইমপোর্ট');
    p('seedSampleData', 'Seed Sample Data', 'নমুনা ডেটা যোগ করুন');
    p('totalCash', 'Total Cash', 'মোট নগদ');
    p('stockValue', 'Stock Value', 'স্টকের মূল্য');
    p('netProfit', 'Net Profit', 'নিট মুনাফা');
    p('netLoss', 'Net Loss', 'নিট ক্ষতি');
    p('totalSell', 'Total Sell', 'মোট বিক্রি');
    p('totalBuy', 'Total Buy', 'মোট কেনা');
    p('due', 'Due', 'বাকি');
    p('duePaid', 'Due Paid', 'পরিশোধিত বাকি');
    p('rentProfit', 'Rent Profit', 'ভাড়ার মুনাফা');
    p('rentDue', 'Rent Due', 'ভাড়া বাকি');
    p('expense', 'Expense', 'খরচ');
    p('toGiveAway', 'To Give Away', 'পরিশোধের জন্য');
    p('sales', 'Sales', 'বিক্রি');
    p('rent', 'Rent', 'ভাড়া');
    p('otherActivities', 'Other Activities', 'অন্যান্য');
    p('stockPurchases', 'Stock Purchases', 'স্টক কেনা');
    p('investorRepayments', 'Investor Repayments', 'বিনিয়োগকারী পরিশোধ');
    p('customerActivity', 'Customer Activity', 'গ্রাহক কার্যক্রম');
    p('searchSales', 'Search sales list...', 'বিক্রির তালিকা খুঁজুন...');
    p('searchProduct', 'Search product to sell...', 'বিক্রির জন্য পণ্য খুঁজুন...');
    p('noMatchingSales', 'No matching sales found', 'কোনো মিল পাওয়া যায়নি');
    p('updateSale', 'Update Sale', 'বিক্রি আপডেট');
    p('productName', 'Product Name', 'পণ্যের নাম');
    p('amountTaka', 'Amount (৳)', 'পরিমাণ (৳)');
    p('cash', 'Cash', 'নগদ');
    p('credit', 'Credit', 'ধার');
    p('edit', 'Edit', 'সম্পাদনা');
    p('delete', 'Delete', 'মুছুন');
    p('buyerOptional', 'Buyer (optional)', 'ক্রেতা (ঐচ্ছিক)');
    p('none', 'None', 'কোনোটি নয়');
    p('quantity', 'Quantity', 'পরিমাণ');
    p('sell', 'Sell', 'বিক্রি');
    p('addBookToRent', 'Add Book to Rent Inventory', 'ভাড়ার জন্য বই যোগান');
    p('bookName', 'Book Name', 'বইয়ের নাম');
    p('pages', 'Pages', 'পৃষ্ঠা');
    p('copies', 'Copies', 'কপি');
    p('add', 'Add', 'যোগ করুন');
    p('availableBooks', 'Available Books', 'উপলব্ধ বই');
    p('rentOutBook', 'Rent Out a Book', 'বই ভাড়া দিন');
    p('customerName', 'Customer Name', 'গ্রাহকের নাম');
    p('days', 'Days', 'দিন');
    p('activeRentals', 'Active Rentals', 'বর্তমান ভাড়া');
    p('markPaid', 'Mark paid', 'পরিশোধ হয়েছে');
    p('return', 'Return', 'ফেরত');
    p('noActiveRentals', 'No active rentals', 'কোনো বর্তমান ভাড়া নেই');
    p('returnedToday', 'Returned Today', 'আজ ফেরত');
    p('allRentalsOnDate', 'All Rentals on This Date', 'এই তারিখের সব ভাড়া');
    p('markUnpaid', 'Mark unpaid', 'অপরিশোধিত');
    p('sellLabel', 'Sell: ', 'বিক্রি: ');
    p('stockLabel', ' | Stock: ', ' | স্টক: ');
    p('matched', 'Matched: ', 'মিলেছে: ');
    p('selected', 'Selected: ', 'নির্বাচিত: ');
    p('backupCopied', 'Backup saved', 'ব্যাকআপ সেভ হয়েছে');
    p('ok', 'OK', 'ঠিক আছে');
    p('importFailed', 'No backup file selected or file is empty.', 'কোনো ব্যাকআপ ফাইল নির্বাচন করা হয়নি বা ফাইল খালি।');
    p('dataImported', 'Data imported successfully', 'ডেটা ইমপোর্ট হয়েছে');
    p('seedDone', 'Sample data seeded with 2+ entries per feature!', 'নমুনা ডেটা যোগ করা হয়েছে!');
    p('addNewAsset', 'Add New Asset', 'নতুন সম্পদ যোগ করুন');
    p('assetNameHint', 'Asset Name (Fridge, Furniture, IT)', 'সম্পদের নাম (ফ্রিজ, আসবাব, আইটি)');
    p('noteOptional', 'Note (optional)', 'নোট (ঐচ্ছিক)');
    p('saveAsset', 'Save Asset', 'সম্পদ সেভ করুন');
    p('assetList', 'Asset List', 'সম্পদের তালিকা');
    p('noAssets', 'No assets added', 'কোনো সম্পদ যোগ করা হয়নি');
    p('dateLabel', 'Date: ', 'তারিখ: ');
    p('outstandingInfo', 'Outstanding balance = sum of all "due" ledger entries - sum of all "payment" entries. Positive means customer owes money.', 'বকেয়া ব্যালেন্স = সব "বাকি" লেজার এন্ট্রির যোগফল - সব "পরিশোধ" এন্ট্রির যোগফল। ধনাত্মক মানে গ্রাহক টাকা পাওনা।');
    p('ledgerInfo', 'Shows every transaction for this customer. "Due" entries increase the balance, "payment" entries decrease it.', 'এই গ্রাহকের প্রতিটি লেনদেন দেখায়। "বাকি" এন্ট্রি ব্যালেন্স বাড়ায়, "পরিশোধ" এন্ট্রি কমায়।');
    p('paymentAmount', 'Payment Amount', 'পরিশোধের টাকা');
    p('close', 'Close', 'বন্ধ');
    p('receivePayment', 'Receive Payment', 'টাকা নিন');
    p('todayDue', 'Today Due', 'আজকের বাকি');
    p('monthlyDue', 'Monthly Due', 'মাসিক বাকি');
    p('filteredDue', 'Filtered Due', 'ফিল্টার করা বাকি');
    p('totalDue', 'Total Due', 'মোট বাকি');
    p('settled', 'Settled', 'পরিশোধিত');
    p('ledger', 'Ledger', 'লেজার');
    p('mobile', 'Mobile', 'মোবাইল');
    p('searchProductAdd', 'Search product to add...', 'পণ্য খুঁজে যোগ করুন...');
    p('dueAmount', 'Due Amount', 'বাকির টাকা');
    p('addToDues', 'Add to Dues', 'বাকিতে যোগ করুন');
    p('paymentSaved', 'Payment saved.', 'পরিশোধ সেভ হয়েছে।');
    p('noCustomers', 'No customers found', 'কোনো গ্রাহক নেই');
    p('noDuesOnDate', 'No dues on selected date', 'নির্বাচিত তারিখে বাকি নেই');
    p('addFirstCustomer', 'Add your first customer above', 'উপরে প্রথম গ্রাহক যোগ করুন');
    p('allSettled', 'All settled', 'সব পরিশোধিত');
    p('outstanding', 'Outstanding: ', 'বকেয়া: ');
    p('ledgerEntries', 'Ledger Entries', 'লেজার এন্ট্রি');
    p('noLedgerEntries', 'No ledger entries yet', 'কোনো লেজার এন্ট্রি নেই');
    p('addCustomerSection', 'Add Customer Section', 'গ্রাহক বিভাগ যোগ করুন');
    p('sectionName', 'Section Name (e.g. Suppliers)', 'বিভাগের নাম (যেমন: সরবরাহকারী)');
    p('pickIcon', 'Pick an icon:', 'একটি আইকন বাছাই করুন:');
    p('cancel', 'Cancel', 'বাতিল');
    p('addSection', 'Add Section', 'বিভাগ যোগ করুন');
    p('name', 'Name', 'নাম');
    p('phone', 'Phone', 'ফোন');
    p('whatsappNo', 'WhatsApp No.', 'হোয়াটসঅ্যাপ নং');
    p('address', 'Address', 'ঠিকানা');
    p('notes', 'Notes', 'নোট');
    p('save', 'Save', 'সেভ করুন');
    p('deleteCustomer', 'Delete Customer', 'গ্রাহক মুছুন');
    p('deleteConfirm', 'Delete "{name}"? This cannot be undone.', '"{name}" মুছবেন? এটি পূর্বাবস্থায় ফেরানো যাবে না।');
    p('delete', 'Delete', 'মুছুন');
    p('addPurchase', 'Add Purchase', 'ক্রয় যোগান');
    p('priceTaka', 'Price (৳)', 'মূল্য (৳)');
    p('date', 'Date', 'তারিখ');
    p('addOrder', 'Add Order', 'অর্ডার যোগান');
    p('orderDescription', 'Order Description', 'অর্ডারের বিবরণ');
    p('dateNeeded', 'Date Needed (dd-MM-yyyy)', 'প্রয়োজনীয় তারিখ (dd-MM-yyyy)');
    p('returnedAndPaid', 'Returned & Paid', 'ফেরত ও পরিশোধিত');
    p('returnedUnpaid', 'Returned • Unpaid', 'ফেরত • অপরিশোধিত');
    p('overdue', 'Overdue', 'মেয়াদোত্তীর্ণ');
    p('active', 'Active', 'সক্রিয়');
    p('addOne', 'Add one', 'একটি যোগ করুন');
    p('addCustomer', 'Add Customer', 'গ্রাহক যোগ করুন');
    p('customerType', 'Customer Type', 'গ্রাহকের ধরন');
    p('note', 'Note', 'নোট');
    p('purchases', 'Purchases', 'কেনা');
    p('noPurchases', 'No purchases recorded', 'কোনো কেনার রেকর্ড নেই');
    p('orders', 'Orders', 'অর্ডার');
    p('noOrders', 'No orders recorded', 'কোনো অর্ডার নেই');
    p('fulfilled', 'Fulfilled', 'সম্পন্ন');
    p('cancelled', 'Cancelled', 'বাতিল');
    p('pending', 'Pending', 'অপেক্ষমাণ');
    p('rentals', 'Rentals', 'ভাড়া');
    p('noRentals', 'No rentals recorded', 'কোনো ভাড়া নেই');
    p('costLabel', 'Cost: ', 'খরচ: ');
    p('paid', 'Paid', 'পরিশোধিত');
    p('unpaid', 'Unpaid', 'অপরিশোধিত');
    p('rentABook', 'Rent a Book', 'বই ভাড়া');
    p('noBooksAvailable', 'No books available. Add books in the Rent tab.', 'বই নেই। ভাড়া ট্যাবে বই যোগ করুন।');
    p('selectBook', 'Select Book', 'বই বাছাই করুন');
    p('noDues', 'No dues recorded', 'কোনো বাকি নেই');
    p('givenLabel', 'Given: ', 'দেওয়া: ');
    p('deadlineLabel', 'Deadline: ', 'শেষ তারিখ: ');
    p('takenLabel', 'Taken: ', 'নেওয়া: ');
    p('cancelledLabel', 'Cancelled: ', 'বাতিল: ');
    p('returnedLabel', 'Returned: ', 'ফেরত: ');
    p('setMonthlyDueDay', 'Set Monthly Due Day', 'মাসিক নির্ধারিত দিন নির্ধারণ');
    p('enterDueDay', 'Enter due day (1-31)', 'নির্ধারিত দিন লিখুন (১-৩১)');
    p('paymentDue', 'Payment Due', 'পরিশোধ বাকি');
    p('editExpense', 'Edit Expense', 'খরচ সম্পাদন');
    p('category', 'Category', 'বিভাগ');
    p('bill', 'Bill', 'বিল');
    p('utilities', 'Utilities', 'ইউটিলিটি');
    p('groceries', 'Groceries', 'মুদিখানা');
    p('transport', 'Transport', 'পরিবহন');
    p('officeSupplies', 'Office Supplies', 'অফিস সরবরাহ');
    p('marketing', 'Marketing', 'মার্কেটিং');
    p('staffSalary', 'Staff Salary', 'স্টাফ বেতন');
    p('maintenance', 'Maintenance', 'রক্ষণাবেক্ষণ');
    p('other', 'Other', 'অন্যান্য');
    p('vendorPayee', 'Vendor / Payee', 'বিক্রেতা / প্রাপক');
    p('amount', 'Amount', 'পরিমাণ');
    p('descriptionNote', 'Description / Note', 'বিবরণ / নোট');
    p('paymentMethod', 'Payment Method', 'পরিশোধ পদ্ধতি');
    p('bank', 'Bank', 'ব্যাংক');
    p('bKash', 'BKash', 'বিকাশ');
    p('card', 'Card', 'কার্ড');
    p('fixed', 'Fixed', 'স্থির');
    p('dueDay', 'Due Day (1-31, optional)', 'নির্ধারিত দিন (১-৩১, ঐচ্ছিক)');
    p('recurring', 'Recurring', 'পুনরাবৃত্তি');
    p('daily', 'Daily', 'দৈনিক');
    p('monthly', 'Monthly', 'মাসিক');
    p('custom', 'Custom...', 'কাস্টম...');
    p('customInterval', 'Custom Interval Days', 'কাস্টম দিনের ব্যবধান');
    p('markAsPaid', 'Mark as Paid', 'পরিশোধ হয়েছে');
    p('deleteExpense', 'Delete Expense', 'খরচ মুছুন');
    p('deleteExpenseConfirm', 'Are you sure you want to delete "{title}"?', 'আপনি কি "{title}" মুছতে চান?');
    p('newExpense', 'New Expense', 'নতুন খরচ');
    p('vendor', 'Vendor', 'বিক্রেতা');
    p('deadline', 'Deadline', 'শেষ তারিখ');
    p('fixedExpense', 'Fixed Expense', 'স্থির খরচ');
    p('overduePayment', 'Overdue Payment', 'মেয়াদোত্তীর্ণ পরিশোধ');
    p('payNow', 'Pay Now', 'এখনই পরিশোধ');
    p('newPurchase', 'New Purchase', 'নতুন কেনা');
    p('cashFrom', 'Cash from', 'নগদ নিয়েছেন');
    p('item', 'Item', 'পণ্য');
    p('shop', 'Shop', 'দোকান');
    p('qty', 'Qty', 'পরিমাণ');
    p('price', 'Price', 'মূল্য');
    p('cost', 'Cost', 'খরচ');
    p('description', 'Description', 'বিবরণ');
    p('itemsTotal', 'Items Total', 'পণ্যের মোট');
    p('otherCostsTotal', 'Other Costs Total', 'অন্যান্য খরচ মোট');
    p('transportTotal', 'Transport Total', 'পরিবহন মোট');
    p('grandTotal', 'Grand Total', 'সর্বমোট');
    p('vehicle', 'Vehicle', 'যানবাহন');
    p('returnedCash', 'Returned Cash', 'ফেরত নগদ');
    p('addPhoto', 'Add Photo', 'ছবি যোগান');
    p('photoTaken', 'Photo Taken', 'ছবি তোলা হয়েছে');
    p('savePurchase', 'Save Purchase', 'ক্রয় সংরক্ষণ');
    p('cashMemoAttached', 'Cash memo attached', 'ক্যাশ মেমো সংযুক্ত');
    p('fixLabel', 'Fix: ', 'স্থির: ');
    p('newTransportCost', 'New Transport Cost', 'নতুন পরিবহন খরচ');
    p('addTransportCost', 'Add Transport Cost', 'পরিবহন খরচ যোগান');
    p('noTransportCosts', 'No transport costs yet', 'এখনো কোনো পরিবহন খরচ নেই');
    p('tapToAdd', 'Tap + to add one', 'একটি যোগ করতে + চাপুন');
    p('editPurchase', 'Edit Purchase', 'কেনা সম্পাদনা');
    p('cashTaken', 'Cash Taken', 'নগদ নেওয়া');
    p('filterByDate', 'Filter by date', 'তারিখ অনুসারে ফিল্টার');
    p('savedPurchases', 'Saved Purchases', 'সেভ করা কেনা');
    p('ownShop', 'Own Shop', 'নিজের দোকান');
    p('addNewCategory', 'Add New Category', 'নতুন বিভাগ যোগ করুন');
    p('enterCategoryName', 'Enter category name', 'বিভাগের নাম লিখুন');
    p('fillRequired', 'Please fill product, buy qty, and price fields.', 'পণ্য, পরিমাণ ও মূল্য দিন।');
    p('buyUnit', 'Buy Unit', 'কেনার একক');
    p('sellUnit', 'Sell Unit', 'বিক্রির একক');
    p('stockFinished', 'Stock finished!', 'স্টক শেষ!');
    p('invalidQty', 'Invalid quantity', 'ভুল পরিমাণ');
    p('dateSelected', 'Date Selected', 'তারিখ বাছাই');
    p('editProduct', 'Edit Product', 'পণ্য সম্পাদনা');
    p('buyQty', 'Buy Qty', 'কেনার পরিমাণ');
    p('buyPrice', 'Buy Price (per buy unit)', 'কেনার মূল্য (প্রতি একক)');
    p('sellPrice', 'Sell Price (per sell unit)', 'বিক্রির মূল্য (প্রতি একক)');
    p('deleteProduct', 'Delete Product', 'পণ্য মুছুন');
    p('addNewProduct', 'Add New Product', 'নতুন পণ্য যোগ করুন');
    p('saveProduct', 'Save Product', 'পণ্য সেভ করুন');
    p('assetName', 'Asset Name', 'সম্পদের নাম');
    p('deleteAsset', 'Delete Asset', 'সম্পদ মুছুন');
    p('noDateSpecificData', 'This page does not have date-specific data.', 'এই পৃষ্ঠায় তারিখ-নির্দিষ্ট তথ্য নেই।');
    p('noProducts', 'No products found', 'কোনো পণ্য নেই');
    p('addFirstProduct', 'Add your first product above', 'উপরে প্রথম পণ্য যোগ করুন');
    p('addAnAsset', 'Add an asset using the form above', 'উপরের ফর্মে সম্পদ যোগ করুন');
    p('shopHint', 'Shop', 'দোকান');
    p('rentCat', 'Rent', 'ভাড়া');
    p('billCat', 'Bill', 'বিল');
    p('utilitiesCat', 'Utilities', 'ইউটিলিটি');
    p('groceriesCat', 'Groceries', 'মুদিখানা');
    p('transportCat', 'Transport', 'পরিবহন');
    p('officeSuppliesCat', 'Office Supplies', 'অফিস সরবরাহ');
    p('marketingCat', 'Marketing', 'মার্কেটিং');
    p('staffSalaryCat', 'Staff Salary', 'স্টাফ বেতন');
    p('maintenanceCat', 'Maintenance', 'রক্ষণাবেক্ষণ');
    p('otherCat', 'Other', 'অন্যান্য');
    p('stockList', 'Stock List', 'স্টক তালিকা');
    p('filterByCategory', 'Filter by Category', 'বিভাগ অনুসারে ফিল্টার');
    p('filterByInvestor', 'Filter by Investor', 'বিনিয়োগকারী অনুসারে ফিল্টার');
    p('all', 'All', 'সব');
    p('products', 'Products', 'পণ্য');
    p('value', 'Value', 'মূল্য');
    p('profit', 'Profit', 'মুনাফা');
    p('completeSale', 'Complete Sale', 'বিক্রি সম্পন্ন');
    p('sellOnCredit', 'Sell on Credit', 'ধারে বিক্রি');
    p('addCategory', 'Add Category', 'বিভাগ যোগ করুন');
    p('assets', 'Assets', 'সম্পদ');
    p('buyLabel', 'Buy: ', 'কেনা: ');
    p('sellPriceLabel', ' .  Sell: ', ' .  বিক্রি: ');
    p('stockLabel2', 'Stock: ', 'স্টক: ');
    p('buyPricePer', 'Buy Price (per buy unit)', 'কেনার মূল্য (প্রতি একক)');
    p('sellPricePer', 'Sell Price (per sell unit)', 'বিক্রির মূল্য (প্রতি একক)');
    p('stockParen', 'Stock (', 'স্টক (');
    p('selectBooks', 'Select Books', 'বই নির্বাচন');
    p('profitSplit', 'Profit Split', 'মুনাফা ভাগ');
    p('cashLoan', 'Cash Loan', 'নগদ ঋণ');
    p('productConsignment', 'Product Consignment', 'পণ্য সরবরাহ');
    p('mudaraba', 'Mudaraba (Profit Sharing)', 'মুদারাবা');
    p('musharaka', 'Musharaka (Joint Venture)', 'মুসারাকা');
    p('cashInvestment', 'Cash Investment', 'নগদ বিনিয়োগ');
    p('mixed', 'Mixed (Cash + Products)', 'মিশ্র (নগদ + পণ্য)');
    p('contractType', 'Contract Type', 'চুক্তির ধরন');
    p('investmentType', 'Investment Type', 'বিনিয়োগের ধরন');
    p('investorName', 'Investor Name', 'বিনিয়োগকারীর নাম');
    p('cashAmount', 'Cash Amount (৳)', 'নগদ টাকা (৳)');
    p('productValue', 'Product Value (৳)', 'পণ্যের মূল্য (৳)');
    p('calcFromStock', 'Calculate from Stock', 'স্টক থেকে গণনা');
    p('durationMonths', 'Duration (Months)', 'মেয়াদ (মাস)');
    p('profitShare', 'Profit Share (%)', 'মুনাফার অংশ (%)');
    p('noProductsForInvestor', 'No products found for this investor name', 'এই নামে কোনো পণ্য নেই');
    p('foundProducts', 'Found ', 'পাওয়া গেছে ');
    p('totalTaka', ' products, total: ৳', ' টি পণ্য, মোট: ৳');
    p('enterInvestment', 'Please enter an investment amount', 'বিনিয়োগের টাকা দিন');
    p('filteringBy', 'Filtering by: ', 'ফিল্টার: ');
    p('remaining', 'Remaining', 'বাকি');
    p('balance', 'Balance', 'ব্যালেন্স');
    p('addInvestor', 'Add Investor', 'বিনিয়োগকারী যোগ করুন');
    p('editInvestor', 'Edit Investor', 'বিনিয়োগকারী সম্পাদনা');
    p('addRepayment', 'Add Repayment', 'পরিশোধ যোগ করুন');
    p('repaymentAmount', 'Amount (৳)', 'টাকা (৳)');
    p('details', 'Details', 'বিস্তারিত');
    p('repay', 'Repay', 'পরিশোধ');
    p('saveInvestor', 'Save Investor', 'বিনিয়োগকারী সেভ করুন');
    p('noInvestors', 'No investors yet. Tap + to add one.', 'কোনো বিনিয়োগকারী নেই। + চাপুন।');
    p('autoTracked', 'All investments are auto-tracked from stock & sales.', 'বিনিয়োগ স্টক ও বিক্রি থেকে ট্র্যাক হয়।');
    p('bought', 'Bought', 'কেনা');
    p('sold', 'Sold', 'বিক্রি');
    p('contract', 'Contract', 'চুক্তি');
    p('investType', 'Invest Type', 'বিনিয়োগের ধরন');
    p('cashInvested', 'Cash Invested', 'নগদ বিনিয়োগ');
    p('productsValue', 'Products Value', 'পণ্যের মূল্য');
    p('totalInvested', 'Total Invested', 'মোট বিনিয়োগ');
    p('duration', 'Duration', 'মেয়াদ');
    p('startDate', 'Start Date', 'শুরুর তারিখ');
    p('yes', 'Yes', 'হ্যাঁ');
    p('no', 'No', 'না');
    p('totalBought', 'Total Bought', 'মোট কেনা');
    p('totalSold', 'Total Sold', 'মোট বিক্রি');
    p('totalProfit', 'Total Profit', 'মোট মুনাফা');
    p('remainingBalance', 'Remaining Balance', 'বাকি ব্যালেন্স');
    p('totalRepaid', 'Total Repaid', 'মোট পরিশোধ');
    p('repayments', 'Repayments', 'পরিশোধ');
    p('noRepayments', 'No repayments yet', 'কোনো পরিশোধ নেই');
    p('investedLabel', 'Invested: ', 'বিনিয়োগ: ');
    p('inStockLabel', 'In Stock: ', 'স্টকে: ');
    p('repaidLabel', 'Repaid: ', 'পরিশোধ: ');
    p('addNote', 'Add a note', 'নোট যোগ করুন');
    p('whatIsThis', 'What is this about?', 'এটি কী নিয়ে?');
    p('skip', 'Skip', 'এড়িয়ে যান');
    p('photoCaptured', 'Photo captured!', 'ছবি তোলা হয়েছে!');
    p('voiceCaptured', 'Voice captured!', 'ভয়েস রেকর্ড হয়েছে!');
    p('clearAllCaptures', 'Clear all captures?', 'সব ক্যাপচার মুছবেন?');
    p('clear', 'Clear', 'মুছুন');
    p('quickNote', 'Quick Note', 'দ্রুত নোট');
    p('writeSomething', 'Write something...', 'কিছু লিখুন...');
    p('noteCaptured', 'Note captured!', 'নোট সেভ হয়েছে!');
    p('recording', 'Recording...', 'রেকর্ডিং...');
    p('voice', 'Voice', 'ভয়েস');
    p('camera', 'Camera', 'ক্যামেরা');
    p('note', 'Note', 'নোট');
    p('listening', 'Listening... tap to stop', 'শুনছে... বন্ধ করতে চাপুন');
    p('clearAll', 'Clear all', 'সব মুছুন');
    p('captureDeleted', 'Capture deleted', 'ক্যাপচার মুছে গেছে');
    p('noCaptures', 'No captures yet', 'কোনো ক্যাপচার নেই');
    p('captureHint', 'Use the buttons above to capture\nphotos, notes, or voice memos', 'উপরের বোতাম ব্যবহার করে ছবি, নোট\nবা ভয়েস নিন');
    p('fromLabel', 'From: ', 'উৎস: ');

    p('buyers', 'Buyers', 'ক্রেতা');
    p('orderGivers', 'Order Givers', 'অর্ডার দাতা');
    p('renters', 'Renters', 'ভাড়াটে');
    p('dueTakers', 'Due Takers', 'বাকি নেয়া');
    p('prospective', 'Prospective', 'সম্ভাব্য');
    p('hintPurchases', 'Products bought by this customer. Each entry records product name, price, and date.', 'এই গ্রাহকের কেনা পণ্য। প্রতিটি এন্ট্রিতে পণ্যের নাম, মূল্য এবং তারিখ রয়েছে।');
    p('hintOrders', 'Pre-orders given by this customer. Shows status: pending → fulfilled → cancelled. Colour coded by days remaining.', 'এই গ্রাহকের দেওয়া প্রি-অর্ডার। স্থিতি দেখায়: pending → fulfilled → cancelled। বাকি দিন অনুসারে রঙিন কোড।');
    p('hintRentals', 'Books currently or previously rented. Cost = rate per period × periods. Overdue items are highlighted in red.', 'বর্তমান বা আগের ভাড়া। খরচ = হার × সময়। বাকি পড়লে লাল দেখাবে।');
    p('hintDue', 'Outstanding balance = sum of all due entries minus payments received.', 'বাকি ব্যালেন্স = সব বাকি - পরিশোধ।');
    p('hintLedger', 'Full transaction history. Each "due" adds to balance, each "payment" reduces it.', 'সব লেনদেনের ইতিহাস। বাকি বাড়ায়, পরিশোধ কমায়।');
    p('dateDdMmYyyy', 'Date (dd-MM-yyyy)', 'তারিখ (dd-MM-yyyy)');
    p('cannotBeUndone', 'This cannot be undone', 'এটি ফেরানো যাবে না');
    p('given', 'Given', 'দেওয়া');
    p('taken', 'Taken', 'নেওয়া');
    p('returned', 'Returned', 'ফেরত');
    p('overdueBy', 'Overdue by', 'বাকি আছে');
    p('dueToday', 'Due TODAY', 'আজকের মধ্যে দিন');
    p('dueIn', 'Due in', 'বাকি');
    p('noLabel', 'No', 'কোনো');
    p('yet', 'yet', 'এখনো');

    p('bangla', 'Bangla', 'বাংলা');
    p('english', 'English', 'ইংরেজি');
    p('language', 'Language', 'ভাষা');
    p('darkTheme', 'Dark Theme', 'ডার্ক থিম');
    p('exitPressAgain', 'Press back again to exit', 'প্রস্থান করতে আবার চাপুন');
    p('toggleView', 'Toggle View', 'ভিউ পরিবর্তন');
    p('totalAssets', 'Total Assets', 'মোট সম্পদ');
    p('noActivitiesToday', 'No activities today', 'আজ কোনো কার্যক্রম নেই');
    p('editSale', 'Edit Sale', 'বিক্রি সম্পাদনা');
    p('editAsset', 'Edit Asset', 'সম্পদ সম্পাদনা');
    p('estimatedValue', 'Estimated Value (৳)', 'আনুমানিক মূল্য (৳)');
    p('commitmentDate', 'Commitment Date', 'প্রতিশ্রুতির তারিখ');
    p('setDate', 'Set Date', 'তারিখ নির্ধারণ');
    p('editCustomer', 'Edit Customer', 'গ্রাহক সম্পাদনা');
    p('monthlyPayback', 'Monthly Payback', 'মাসিক পরিশোধ');
    p('repayBy', 'Repay by', 'পরিশোধের তারিখ');
    p('items', 'Items', 'পণ্য');
    p('otherCosts', 'Other Costs', 'অন্যান্য খরচ');
    p('transportCosts', 'Transport Costs', 'পরিবহন খরচ');
    p('investorProfitSplit', 'Investor Profit Split', 'বিনিয়োগকারীর মুনাফা বন্টন');
    p('rentPaid', 'Rent Paid', 'ভাড়া দেওয়া');

    return {'en': e, 'bn': b};
  }

  static String tr(String key) {
    return _data[localeNotifier.value]?[key] ?? _data['en']?[key] ?? key;
  }
}
